---
engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.md"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- db/
- test/
